### ISSUE TITLE
CAMBIAR ENUNCIADO DE LA RUTA documentos/0613_Servidor/032_middlewares.md

### ISSUE THREAD

**Issue by Manuelfsr** [2DAW-CarlosIII/marcapersonalFP_REA#11]
El siguiente enunciado está incorrecto, no corresponde con el ejemplo: 
Por ejemplo podríamos crear un filtro que redirija al home si el usuario tiene menos de 18 años y en otro caso que le permita acceder a la ruta.

Modificar el enunciado para que se adapte al ejemplo.

**Comment by albsierra** [comment]
closed by [commit d4031ff](https://github.com/2DAW-CarlosIII/marcapersonalFP_REA/commit/d4031ffde138b1b89fdd2b490e7160079afa4914)
