### ISSUE TITLE
Error de sintaxis a la hora de llamar al método with por width

### ISSUE THREAD

**Issue by Zaidanxp** [2DAW-CarlosIII/marcapersonalFP_REA#12]
https://github.com/2DAW-CarlosIII/marcapersonalFP_REA/blob/f45df1924a01a181c21216a7ecb094b9f96427af/documentos/0613_Servidor/036_ejerciciosControladores.md?plain=1#L27

**Comment by albsierra** [comment]
Solved by [e5f4cdc](https://github.com/2DAW-CarlosIII/marcapersonalFP_REA/commit/e5f4cdc742acebb9fa7b7e0d9cae242e5d9ff2b5)
