### ISSUE TITLE
Entre migrate y fresh falta dos puntos ":"

### ISSUE THREAD

**Issue by Zaidanxp** [2DAW-CarlosIII/marcapersonalFP_REA#13]
https://github.com/2DAW-CarlosIII/marcapersonalFP_REA/blob/f3bca1e36b245ce91496a3cfe3b4adb9cd67d90e/documentos/0613_Servidor/047_ejerciciosBD.md?plain=1#L12

**Comment by albsierra** [comment]
Closed by #[543fe84](https://github.com/2DAW-CarlosIII/marcapersonalFP_REA/commit/543fe8498f464cd7cf794dd581ac1966024df07c)
