### ISSUE TITLE
Sustituir title por docente_id

### ISSUE THREAD

**Issue by Zaidanxp** [2DAW-CarlosIII/marcapersonalFP_REA#14]
https://github.com/2DAW-CarlosIII/marcapersonalFP_REA/blob/f3bca1e36b245ce91496a3cfe3b4adb9cd67d90e/documentos/0613_Servidor/047_ejerciciosBD.md?plain=1#L61

# Columna Docente_id
En la columna `docente_id` de la tabla Proyecto almacenamos el identificador del docente asignado al proyecto, no la propiedad `title` que además, no se encuentra definida en el objeto Proyecto.

**Comment by albsierra** [comment]
solucionado en #[e0cd21e](https://github.com/2DAW-CarlosIII/marcapersonalFP_REA/commit/e0cd21ef88da256c9c73406325775737a671c93d)
