### ISSUE TITLE
Falta static

### ISSUE THREAD

**Issue by JonatanMolina91** [2DAW-CarlosIII/marcapersonalFP_REA#15]
https://github.com/2DAW-CarlosIII/marcapersonalFP_REA/blob/e0cd21ef88da256c9c73406325775737a671c93d/documentos/0613_Servidor/047_ejerciciosBD.md?plain=1#L54

Si no declaras el array como static no funciona, estaría bien  ponerlo en la documentación, gracias. ^^

**Comment by albsierra** [comment]
En el caso de la diferenciación entre método de instancia o de clase, prefiero que os topéis con el error.

Si lo pongo, no hay manera de que diferenciéis cuando se trata de un método (o propiedad) de clase de un método (o propiedad) de instancia.

Espero que, una vez que os habéis tenido que enfrentar al problema, lo podáis consolidar.

Veremos.
