### ISSUE TITLE
unserialize

### ISSUE THREAD

**Issue by JonatanMolina91** [2DAW-CarlosIII/marcapersonalFP_REA#16]
https://github.com/2DAW-CarlosIII/marcapersonalFP_REA/blob/e0cd21ef88da256c9c73406325775737a671c93d/documentos/0613_Servidor/047_ejerciciosBD.md?plain=1#L77

Falta explicar que el array de metadatos lo guardamos de forma serializada y que hay que usar el unserialize() para poder recuperar dichos datos, estaría bien que lo pusieras, gracias.

**Comment by albsierra** [comment]
Corregido en #[e130bec](https://github.com/2DAW-CarlosIII/marcapersonalFP_REA/commit/e130becfdf5952e1a27cd3f5366aafd33648bceb)
