### ISSUE TITLE
Falta el script main.js

### ISSUE THREAD

**Issue by Zaidanxp** [2DAW-CarlosIII/marcapersonalFP_REA#9]
https://github.com/2DAW-CarlosIII/marcapersonalFP_REA/blob/0322a2a516778dc1a635e02280a9d1063f3a948b/documentos/0613_Servidor/0271_reutilizarPlantilla.md?plain=1#L42

**Comment by albsierra** [comment]
Resuelto en el _commit_ [[c4a0e8b](https://github.com/2DAW-CarlosIII/marcapersonalFP_REA/commit/c4a0e8bc1aa7ecfc83028451018a1ac93160b6c0)](https://github.com/2DAW-CarlosIII/marcapersonalFP_REA/commit/c4a0e8bc1aa7ecfc83028451018a1ac93160b6c0)
